trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CYPRESS_CACHE_FOLDER: /home/vsts/.cache/Cypress

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'cypress | "$(Agent.OS)" | package-lock.json'
      path: $(CYPRESS_CACHE_FOLDER)
      cacheHitVar: CYPRESS_CACHE_RESTORED
    displayName: 'Restore Cypress Binary from Cache'

  - script: |
      npm install --force
    displayName: 'Install npm dependencies'

  - script: |
      npx cypress verify
    displayName: 'Verify Cypress binary'

  - script: |
      sudo apt-get update
      sudo apt-get install -y xvfb
    displayName: 'Install Xvfb'

  - script: |
      xvfb-run -a npx cypress run
    displayName: 'Run Cypress tests'
    env:
      CI: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/videos'
      ArtifactName: 'cypress-videos'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/screenshots'
      ArtifactName: 'cypress-screenshots'
    condition: succeededOrFailed()
