# azure-pipelines.yml

trigger:
  branches:
    include:
      - main  # Change to your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  CYPRESS_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/Cypress

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npx cypress install
      chmod +x ./node_modules/.bin/cypress
    displayName: 'Install and Fix Cypress Binary Permissions'

  - script: |
      npx cypress run
    displayName: 'Run Cypress tests'

  # Optional: Publish test results if using JUnit reporter
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/cypress/results/*.xml'
      testRunTitle: 'Cypress Tests'
    condition: succeededOrFailed()

  # Optional: Publish videos/screenshots from Cypress
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/videos'
      ArtifactName: 'cypress-videos'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/screenshots'
      ArtifactName: 'cypress-screenshots'
    condition: succeededOrFailed()
