trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CYPRESS_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/Cypress

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm install --force
    displayName: 'Install Dependencies & Cypress'

  - script: |
      echo "Verifying Cypress binary..."
      npx cypress verify
    displayName: 'Verify Cypress Binary'

  - script: |
      npx cypress run
    displayName: 'Run Cypress Tests'

  # Optional: Publish screenshots and videos
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/videos'
      ArtifactName: 'cypress-videos'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/screenshots'
      ArtifactName: 'cypress-screenshots'
    condition: succeededOrFailed()
