trigger:
  branches:
    include:
      - main  # Change this to your active development branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  CYPRESS_CACHE_FOLDER: /home/vsts/.cache/Cypress

steps:
  # ✅ Step 1: Use Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # ✅ Step 2: Cache Cypress Binary across builds
  - task: Cache@2
    inputs:
      key: 'cypress | "$(Agent.OS)" | package-lock.json'
      path: $(CYPRESS_CACHE_FOLDER)
      cacheHitVar: CYPRESS_CACHE_RESTORED
    displayName: 'Restore Cypress Binary from Cache'

  # ✅ Step 3: Install project dependencies
  - script: |
      npm install --force
    displayName: 'Install npm dependencies'

  # ✅ Step 4: Install Cypress (skips download if cached binary is present)
  - script: |
      npm install --force
    displayName: 'Verify Cypress Installation'
    
  - script: |
      chmod +x ./node_modules/.bin/cypress
    displayName: 'Fix Cypress binary permissions'

  # ✅ Step 6: Run Cypress tests
  - script: |
      npx cypress run
    displayName: 'Run Cypress tests'


  # ✅ Step 7: Publish screenshots/videos on failure
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/videos'
      ArtifactName: 'cypress-videos'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/screenshots'
      ArtifactName: 'cypress-screenshots'
    condition: succeededOrFailed()
